site_name: OSU Extension Website User Guide

site_description: 'OSU Extension Web-guide'
theme:
  name: readthedocs
extra_css:
  - css/extra.css
google_analytics: ['UA-109218015-4', 'osu-eesc.github.io']
site_favicon: favicon.ico
nav:
  - Home: index.md
